name: Generer Inventaire JSON
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    # On force explicitement l'autorisation d'écriture pour ce Job
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generer JSON
        run: python generer_json.py

      - name: Commit et Push
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          
          if [ -f "books-list.json" ]; then
            git add books-list.json
            git commit -m "Mise à jour automatique de la liste des livres" || echo "Aucun changement à commiter"
            git push
          else
            echo "Erreur : Le fichier books-list.json n'a pas été généré."
            exit 1
          fi
